# Generated by Django 4.2.5 on 2023-09-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsowebapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='passowrd',
        ),
    ]
