# Generated by Django 4.2.5 on 2023-09-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsowebapp', '0002_rename_description_item_passowrd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='passowrd',
            new_name='email',
        ),
        migrations.AddField(
            model_name='item',
            name='password',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
