# Generated by Django 4.2.5 on 2023-10-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsowebapp', '0003_rename_passowrd_item_email_item_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Login',
        ),
    ]
